### PR TITLE
create group-function

### PR DESCRIPTION
**Pull request by KatsuyaHirayasu**
# WHAT

creating & editing group
indicating group names on the view

# WHY

if we made some mistakes and want to join someone to our groups, we can correct these easily.
also we can create a closed group and see on the view.

### CODE REVIEW

**Comment by ky3090** [comment]
一応viewをgyazoで撮って見せてください！

**Comment by KatsuyaHirayasu** [comment]
https://gyazo.com/1e1e9cae84f2c7b344f8def6461fdcd4
https://gyazo.com/ce19e7589d73cb73681c3afbd1e0e266
こんな感じになってます。

**Comment by ky3090** [comment]
マージでメッセージ機能のところでみますね

**Comment by ky3090** [comment]
lgtm3

**Pull request merged**
